---

- name: Add the Signal Packages APT key
  ansible.builtin.apt_key:
    url: https://updates.signal.org/desktop/apt/keys.asc
    state: present

- name: Add Signal Repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://updates.signal.org/desktop/apt xenial main"
    state: present
    filename: signal-desktop

- name: Install Signal Desktop
  ansible.builtin.apt:
    name: signal-desktop
    update_cache: yes
    state: present

