---
- name: Add Signal repo using key from URL
  ansible.builtin.deb822_repository:
    name: signal-desktop
    types: [deb]
    uris: "https://updates.signal.org/desktop/apt"
    architectures: [amd64]
    components: [main]
    suites: [xenial] # "{{ ansible_distribution_release|lower }}" Signal only supports xenial ... but it seems to work everywhere :shrug:
    signed_by: https://updates.signal.org/desktop/apt/keys.asc
    state: present
    enabled: true
  become: true
  become_user: root

- name: Install Signal Desktop
  ansible.builtin.apt:
    name: signal-desktop
    update_cache: true
    state: present
  ignore_errors: "{{ ansible_check_mode }}"
  become: true
  become_user: root
