---
- name: Remove legacy apt file
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/signal-desktop.list
    state: absent

- name: Add Signal repo using key from URL
  ansible.builtin.deb822_repository:
    name: signal-desktop
    types: [deb]
    uris: "https://updates.signal.org/desktop/apt"
    architectures: [amd64]
    components: [main]
    suites: [xenial] # "{{ ansible_distribution_release|lower }}"
    signed_by: https://updates.signal.org/desktop/apt/keys.asc
    state: present
    enabled: true

- name: Install Signal Desktop
  ansible.builtin.apt:
    name: signal-desktop
    update_cache: true
    state: present
